# Generated by Django 4.2.13 on 2024-07-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_author_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='birthday',
            new_name='post',
        ),
    ]
